# Site settings
title: Walenoh
header-img: img/home-bg.jpg
email: Walenoh@gmail.com
description: "Write your site description here."
#baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://www.walenoh.com"
twitter_username: walenoh
github_username:  walenoh
facebook_username: 

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
